### PR TITLE
Make compatible with kitspace.org

### PR DESCRIPTION
**Pull request by kasbah**
Hey, I added the files necessary to add your project on [kitspace.org](https://kitspace.org). Here is a [preview](http://add-bbq10kbd.preview.kitspace.org/boards/github.com/kitspace-forks/bbq10kbd_breakout/) of what it will look like. If you are happy to add it, just merge these changes. If added the Kitspace page will stay in sync with the Github repo (with a max delay of 24hrs). 

This BOM is quite simple, but if you like the idea of adding your projects I could take a look at a more complicated one where the 1-click-BOM functionality will be more worth it.

### CODE REVIEW

**Comment by arturo182** [comment]
Hmm, I thought the BOM was wrong cause it says 100uF but it's actually the schematic that is wrong, it should be 100nF = 0.1uF. Could you change that in the BOM so someone doesn't buy the wrong one? I will update in the design too.

**Comment by kasbah** [comment]
Sure, I was confused about that too. I made the changes and also found some SKUs for the headers. 

The BOM was made by importing the `kicad_pcb` directly into the [BOM Builder](https://kitspace.org/bom-builder/). I also have some [kicad scripts](https://github.com/kitspace/1clickBOM/tree/master/output_scripts/kicad) that could generate something similar from the `sch` if all the info is in there. After that you could use KiField to keep everything in sync, but it's probably overkill for these 3 line items :)

**Comment by arturo182** [comment]
Thank you :)

**Comment by kasbah** [comment]
It's up! https://kitspace.org/boards/github.com/arturo182/bbq10kbd_breakout/

**Pull request merged**
